### ISSUE TITLE
时间戳精度问题

### ISSUE THREAD

**Issue by hurae** [messi-wpy/TouchEventCollect#2]
- 建议直接使用原生的**timestamp**
- 时间要精确到**毫秒**
- 现在的情况下，**一次滑动操作**中看不到**时间戳的变化**

**Comment by hurae** [comment]
我通过分析网络数据包看到发送的数据包如下：
> [{"statu":0,"time":20190204,"x":915,"y":1174}]

- 时间实际**只精确到天**
- 实际上日期都可以不要，只要几点钟几分几秒几毫秒就可以了
- 或者改为从开始捕获经过的秒数和毫秒数

**Comment by messi-wpy** [comment]
现在是精确到秒，毫秒也可以
用的是system.currenttime ，就是原生的。。。
精确到毫秒可以

**Comment by hurae** [comment]
我不懂java的语言细节。我看到你一开始收集的确实是精确到毫秒的，但是后来在发送网络数据包时可以看到只有日期而并没有精确的时间。
