### ISSUE TITLE
空文件阻塞运行

### ISSUE THREAD

**Issue by hurae** [messi-wpy/TouchEventCollect#5]
- 当由于未知原因导致最新的记录文件为空时，发送不会成功，也不会失败
- 点击Send以后，一段时间内无法再查看文件列表或文件内容，若干时间后恢复响应
- 同时GETEVENT也不会提示开始数据收集，QUIT也不会提示结束收集

**Comment by hurae** [comment]
- 不确定是不是空文件，但是至少查看文件内容时看不到内容。
- 并且点击SEND也不会成功。

**Comment by messi-wpy** [comment]
先看一下。。。是空的话就别send了呗

**Comment by messi-wpy** [comment]
这真的不就是我们实验的工具，我们告诉他怎么操作就行，，，所以当时我没有做到的那么精细，每一个错误都做了处理
