### ISSUE TITLE
statu字段无效使用

### ISSUE THREAD

**Issue by hurae** [messi-wpy/TouchEventCollect#8]
分析网络数据包可得其中一次完整请求内容如下：（该应用为谷歌输入法）

> {"List":[[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}]],"appName":"latin","userID":589}

- 可以发现，所有的statu字段值**均为0**，并且所有其它请求中statu均为0
- 文件中的action_up, action_down并**没有体现**出来
- 导致无法分辨点击和滑动操作

**Comment by messi-wpy** [comment]
这是故意的，因为设置这个status本身就没什么用，，，
每个list都是一次操作

**Comment by messi-wpy** [comment]
后来因为麻烦就没有把它删掉

**Comment by hurae** [comment]
那么我们是如何分辨点击和滑动的？

**Comment by hurae** [comment]
> 
> 
> 这是故意的，因为设置这个status本身就没什么用，，，
> 每个list都是一次操作

我观察后认为，每个list是一个应用内的所有操作。下一条数据包中式另外一个应用。对比本地文件的记录也可以确认这一点。
