### ISSUE TITLE
记录文件内容解析错误

### ISSUE THREAD

**Issue by hurae** [messi-wpy/TouchEventCollect#9]
分析网络数据包可得其中一次完整请求内容如下：（该应用为谷歌输入法）

> {"List":[[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}],[{"statu":0,"time":20190204,"x":915,"y":1174}]],"appName":"latin","userID":589}

- 可以发现，此次记录中所有的坐标均为"x":915,"y":1174
- 本地记录文件中相关内容为：
> com.android.systemui
> action_up
> 省略若干次滑动操作（完整的down-坐标点-up模式）
> action_down
> 20190204-211023(915,1174)
> com.example.messi_lp.touchdemo
> com.google.android.inputmethod.latin
> 【本地记录文件结尾】

- 猜测因为预设逻辑为处理“完整的down-坐标点-up模式”的数据，但实际记录得到为down之后切换到另一个应用并以up开头，导致代码的非预期行为
- 导致“action_down之后切换到另一个应用，并以action_up开头”的原因猜测是“使用了安卓的最近任务切换功能，并且最近任务视图中的操作不属于任何一个应用”，也可能与测试机使用了实体键来切换应用有关

**Comment by messi-wpy** [comment]
我觉得不应该出现这种情况的，你可以看看[这段代码](https://github.com/messi-wpy/TouchEventCollect/blob/master/app/src/main/java/com/example/messi_lp/touchdemo/FileConvert.java)的`readFromFile()`方法，而且只有遇到up才会记录这次数据。从down开始，所以一开始如果只有up，那么直到第一次down出现他才会记录。

坐标点和应用名称的出现不是很规整，具体处理都在那个方法里

**Comment by messi-wpy** [comment]
而且输出法是点击，点击事件，按了两三次后，他才会一下子写出来，几个点，所以如果只按一次，很可能这个点就不会记录出来，这我都做了取舍，，
你不信可以连接手机，在linux终端输入adb shell getevent -I  命令自己试一下

**Comment by hurae** [comment]
我使用AS进行调试时已经观察到了这一现象。同时我还发现短时间（大约一分钟左右）的收集不会生成包含操作的文件，只有app名称。而长时间（密集的滑动操作若干分钟）的操作则会发送失败。

**Comment by hurae** [comment]
对比数据包和本地文件，可以发现不只是坐标的问题，而且根本就是解析到了错误的应用上

**Comment by hurae** [comment]
now it's fine
